function [graph_features_local] = gui_featurematrix_local

graph_features_local = {[],'Degree','degree';...
                    [],'Eccentricity','eccentricity';... 
                    [],'Node Betweenness','nodebetweenness';...
                    [],'Local Efficiency','efficlocal';...
                    [],'Clustering Coeff','nodeclusteringcoeff';...
                    [],'Strength','strength';...
                    [],'Participation Coeff','participationcoeff';...
                    };   