function [graph_features power_features] = gui_featurematrix

graph_features = {[],'Avg Clustering Coefficient','clusteringcoeff';...
                    [],'Global Efficiency','efficglobal';... 
                    [],'Path Length','avgpath';...
                    [],'Modularity','modularitylouvain';...
                    [],'Mean Coherence','meancoherence';...
                    [],'Assortativity','assortativity';...
                    [],'Density','density';...
                    [],'Radius','radius';...
                    [],'Diameter','diameter';...
                    [],'Small Worldness','smallworldness'...
                    };   
                
power_features = {[],'Relative Power','rel_power';...
                    [],'Absolute Power','abs_power'};