function [graph_features_local_cluster] = gui_featurematrix_local_cluster

graph_features_local_cluster = {[],'Degree','degree';...
                    [],'Eccentricity','eccentricity';... 
                    [],'Node Betweenness','nodebetweenness';...
                    [],'Local Efficiency','efficlocal';...
                    [],'Clustering Coeff','nodeclusteringcoeff';...
                    [],'Strength','strength';...
                    [],'Participation Coeff','participationcoeff';...
                    %[],'Intraregional Conn','intraconn';...
                    %[],'Interregional Conn','interconn';...
                    };   